export enum ClientWebSocketType {
	NONE = "NONE",
	USER_ADDED_TO_FOLLOWING = "USER_ADDED_TO_FOLLOWING",
	USER_REMOVED_FROM_FOLLOWING = "USER_REMOVED_FROM_FOLLOWING",
	POST_FROM_HASHTAG_FEED_LIKED = "POST_FROM_HASHTAG_FEED_LIKED"
}